<style TYPE="text/css">
<!--
P {font-size: 10pt; text-align: left; font-family: "Comic Sans MS", "Arial"}

P.paragraph {font-size: 9pt; text-align:left; font-color: black; font-family: "Comic Sans MS", "Arial"}

P.small	{font-size: 9pt; text-align: left; font-family: "Arial", "Comic Sans MS"}

P.large	{font-size: 11pt; text-align: left; font-family: "Comic Sans MS", "Arial"}

P.x14 {font-size: 14pt; font-family: "Comic Sans MS", "Arial"; font-color: black}

TD.THREE {font-size: 9pt; font-family: "Comic Sans MS", Arial; font-color: "mediumslateblue"; text-align: left; font-weight: bold}

TD.TWO {font-size: 10pt; font-family: "Comic Sans MS", Arial; font-color: "mediumslateblue"; text-align: center; font-weight: bold}

TD.ONE {font-size: 14pt; font-family: "Comic Sans MS", Arial; font-color: "mediumslateblue"; text-align: center; font-weight: bold}

TD {font-size: 9pt; font-family: "Comic Sans MS", "Arial"; font-color: black}

TD.x08 {font-size: 8pt; font-family: "Comic Sans MS", "Arial"; font-color: black}

TD.x09 {font-size: 9pt; font-family: "Comic Sans MS", "Arial"; font-color: black}

TD.x10 {font-size: 10pt; font-family: "Comic Sans MS", "Arial"; font-color: black}

TD.x11 {font-size: 11pt; font-family: "Comic Sans MS", "Arial"; font-color: black}

TD.x12 {font-size: 12pt; font-family: "Comic Sans MS", "Arial"; font-color: black}

TD.x13 {font-size: 13pt; font-family: "Comic Sans MS", "Arial"; font-color: black}

TD.x14 {font-size: 14pt; font-family: "Comic Sans MS", "Arial"; font-color: black}

TD.x16 {font-size: 16pt; font-family: "Comic Sans MS", "Arial"; font-color: black}

TD.arial_10 {font-size: 10pt; font-family: "Arial", "Arial"; font-color: black}

TD.arial_11 {font-size: 11pt; font-family: "Arial", "Arial"; font-color: black}

TD.paragraph {font-size: 10pt; font-family: "Comic Sans MS","Arial"; font-color: black; text-align:left}

TD.head {font-size: 8pt; font-family: "Comic Sans MS", "Arial"; font-weight: bold}

TH {font-size: 8pt; font-family: "Comic Sans MS", "Arial"; font-color: white; font-weight: bold}
-->
</style>
